#!/bin/sh
# f2ehook
PATH="/Users/jiewei.ljw/work/fe/aefe-mobile-global/node_modules/@ali/f2ehint-hook/node_modules/.bin:/Users/jiewei.ljw/.config/yarn/link/node_modules/.bin:/Users/jiewei.ljw/work/fe/aefe-mobile-global/node_modules/@ali/f2ehint-hook/node_modules/.bin:/Users/jiewei.ljw/.config/yarn/link/node_modules/.bin:/Users/jiewei.ljw/.nvm/versions/node/v7.5.0/lib/node_modules/tnpm/node_modules/yarn/bin/node-gyp-bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/git:/usr/local/opt/subversion/bin:/Users/jiewei.ljw/.jenv/shims:/Users/jiewei.ljw/.jenv/bin:/Users/jiewei.ljw/maven/bin::/usr/local/opt/pyenv/shims:/usr/local/opt/pyenv/bin:/usr/local/opt/rbenv/shims:/usr/local/opt/rbenv/bin:/Users/jiewei.ljw/.nvm/versions/node/v7.5.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jiewei.ljw/Library/Android/sdk/tools:/Users/jiewei.ljw/Library/Android/sdk/platform-tools"
[ -f package.json ] && cat package.json | grep -q '"commithook"\s*:'
[ $? -ne 0 ] && exit 0
npm run commithook --silent
if [ $? -ne 0 ]; then
  echo
  echo "git-hook: pre-commit hook failed (add --no-verify to bypass)"
  echo
  exit 1
fi